name: Daily README Update

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  snack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            main/github-snake.svg
            main/github-snake-dark.svg?palette=github-dark
      - uses: casperdcl/push-dir@v1
        with:
          message: Snack
          branch: snack
          dir: snack
          history: false
